export const ON_STATE_MOUNT = '@@App/ON_STATE_MOUNT';
export const ON_STATE_MOUNT_SUCCESS = '@@App/ON_STATE_MOUNT_SUCCESS';
export const ON_STATE_MOUNT_ERROR = '@@App/ON_STATE_MOUNT_ERROR';

export const ON_DASHBOARD_MOUNT = '@@App/ON_DASHBOARD_MOUNT';
export const ON_DASHBOARD_MOUNT_SUCCESS = '@@App/ON_DASHBOARD_MOUNT_SUCCESS';
export const ON_DASHBOARD_MOUNT_ERROR = '@@App/ON_DASHBOARD_MOUNT_ERROR';

export const ON_ADD_LOCATION = '@@DASHBOARD/ON_ADD_LOCATION';
export const ON_ADD_LOCATION_SUCCESS = '@@DASHBOARD/ON_ADD_LOCATION_SUCCESS';
export const ON_ADD_LOCATION_ERROR = '@@DASHBOARD/ON_ADD_LOCATION_ERROR';

export const ON_REMOVE_LOCATION = '@@DASHBOARD/ON_REMOVE_LOCATION';
export const ON_REMOVE_LOCATION_SUCCESS = '@@DASHBOARD/ON_REMOVE_LOCATION_SUCCESS';
export const ON_REMOVE_LOCATION_ERROR = '@@DASHBOARD/ON_REMOVE_LOCATION_ERROR';

export const ON_REMOVE_CITY_SUCCESS = '@@DASHBOARD/ON_REMOVE_CITY_SUCCESS';
export const ON_REMOVE_CITY_ERROR = '@@DASHBOARD/ON_REMOVE_CITY_ERROR';

export const ON_ADD_COUNTRY_SUCCESS = '@@DASHBOARD/ON_ADD_COUNTRY_SUCCESS';
export const ON_ADD_COUNTRY_ERROR = '@@DASHBOARD/ON_ADD_COUNTRY_ERROR';

export const ON_ADD_CITY_SUCCESS = '@@DASHBOARD/ON_ADD_CITY_SUCCESS';
export const ON_ADD_CITY_ERROR = '@@DASHBOARD/ON_ADD_CITY_ERROR';

export const ON_REMOVE_FORECAST = '@@DASHBOARD/ON_REMOVE_FORECAST';

export const ON_FETCH_NEW_FORECAST = '@@FORECAST/ON_FETCH_NEW_FORECAST';
export const ON_FETCH_NEW_FORECAST_SUCCESS = '@@FORECAST/ON_FETCH_NEW_FORECAST_SUCCESS';
export const ON_FETCH_NEW_FORECAST_ERROR = '@@FORECAST/ON_FETCH_NEW_FORECAST_ERROR';

export const ON_LOCATION_VALID = '@@DASHBOARD/ON_LOCATION_VALID';
export const ON_LOCATION_REVOKE = '@@DASHBOARD/ON_LOCATION_REVOKE';

export const ON_FORECAST_LOCATION_CLICK = '@@DASHBOARD/ON_FORECAST_LOCATION_CLICK';
export const ON_FORECAST_LOCATION_CLICK_SUCCESS = '@@DASHBOARD/ON_FORECAST_LOCATION_CLICK_SUCCESS';
export const ON_FORECAST_LOCATION_CLICK_ERROR = '@@DASHBOARD/ON_FORECAST_LOCATION_CLICK_ERROR';

export const ON_DETAILED_FORECAST_MOUNT = '@@DETAILED_FORECAST/ON_DETAILED_FORECAST_MOUNT';
export const ON_DETAILED_FORECAST_MOUNT_SUCCESS = '@@DETAILED_FORECAST/ON_DETAILED_FORECAST_MOUNT_SUCCESS';
export const ON_DETAILED_FORECAST_MOUNT_ERROR = '@@DETAILED_FORECAST/ON_DETAILED_FORECAST_MOUNT_ERROR';

export const ON_FETCH_CITIES = '@@localStorage/ON_FETCH_CITIES';
export const ON_FETCH_CITIES_SUCCESS = '@@localStorage/ON_FETCH_CITIES_SUCCESS';
export const ON_FETCH_CITIES_ERROR = '@@localStorage/ON_FETCH_CITIES_ERROR';

export const ON_FETCH_COUNTRIES = '@@localStorage/ON_FETCH_COUNTRIES';
export const ON_FETCH_COUNTRIES_SUCCESS = '@@localStorage/ON_FETCH_COUNTRIES_SUCCESS';
export const ON_FETCH_COUNTRIES_ERROR = '@@localStorage/ON_FETCH_COUNTRIES_ERROR';